name: utility_tools
description: A collection of utility functions for Flutter and Dart, including helpers for process utils/check duplicate files.


version: 1.0.0+4

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  crypto: ^3.0.6
  path: ^1.9.1
  http: ^1.5.0
  google_fonts: ^6.2.1
  window_manager: ^0.5.1
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  image: ^4.5.4
  win32: ^5.14.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.11

flutter:

  uses-material-design: true




